### ISSUE TITLE
Make eless run on emacs 22.1

### ISSUE THREAD

**Issue by sshaw** [kaushalmodi/eless#21] opened 2018-02-13 22:53 UTC
Given that this is a shell command, I would not rely on users: 

1. Being Emacs users
1. Having a modern version of emacs on their system or one named "emacs" in their path 

In my case OS X ships with Emacs 22, which does not support these functions (I think only versions greater that 24.4 do?). 

I think `eval-after-load` and `string-match` would suffice. 

Also, I usually download Emacs from [here](https://emacsformacosx.com/). In this case there is no binary called `emacs`. It's called `Emacs`.

**Comment by kaushalmodi** [comment] 2018-02-13 23:52
> Also, I usually download Emacs from here. In this case there is no binary called emacs. It's called Emacs.

That's a bit odd, but in any case, I have opened https://github.com/kaushalmodi/eless/issues/22. Should be easy to implement.

**Comment by kaushalmodi** [comment] 2018-02-14 03:06
> I think eval-after-load and string-match would suffice.

You are correct. I have made that change. Please try the latest master.

**Comment by sshaw** [comment] 2018-02-14 14:01
Currently I get an `Invalid regex: "Invalid regular expression"` error. But, this is  with system emacs 22 (OS X 10.9.5). Not clear what the source is. 

I have a more recent version of OS X (well, "macOS") that I will try with later today.

**Comment by kaushalmodi** [comment] 2018-02-14 17:37
> Currently I get an Invalid regex: "Invalid regular expression" error.

Let's continue the discussion for this here: https://github.com/kaushalmodi/eless/issues/25.

Once **just running** `eless` (not building [[Requirements][1]]) works on emacs 23 for you, we can close this issue.


[1]: https://eless.scripter.co/#requirements

**Comment by kaushalmodi** [comment] 2018-02-16 03:17
@sshaw I'll close this issue once you confirm that `eless` runs fine on emacs 22.1.

**Comment by sshaw** [comment] 2018-02-16 04:12
Working here too. Very nice. 🎉

One thing I did notice (unrelated) are broken pipe errors from [this](https://github.com/kaushalmodi/eless/blob/8a3ec9ad7241817b419888d9a6a82fa753df4a23/eless#L232), which is always ran.

**Comment by kaushalmodi** [comment] 2018-02-16 04:14
> One thing I did notice (unrelated) are broken pipe errors from this, which is always ran.

I didn't follow. What do they looks like? How to reproduce?

**Comment by sshaw** [comment] 2018-02-16 04:35
From the eless repo run:
```bash
git --no-pager log |  ./eless
```

Then quit and you'll see:

```
./eless: line 232: echo: write error: Broken pipe
```

This is because `$(echo "${piped_data}" | head -n 10)` will run. Since `head` is closing the pipe after 10 lines `echo` complains. 

Fix is easy:

```bash
$(echo "${piped_data}" 2>/dev/null | head -n 10)
```

But instead of loading a possibly very big string into a variable when piped (and defeating some of the purpose of a pipe), why not just `cat` to file immediately? There's no need o [do it via `echo` later (https://github.com/kaushalmodi/eless/blob/8a3ec9ad7241817b419888d9a6a82fa753df4a23/eless#L520) .

Then you can just say `$(head -n $tempfile)`

**Comment by kaushalmodi** [comment] 2018-02-16 04:44
> Then quit and you'll see:

I did as you suggested, hit `q`, but I don't see any error.

![no-broken-pipe](https://user-images.githubusercontent.com/3578197/36293818-2766fb3e-12aa-11e8-97a7-14d97d9e6170.gif)

**Comment by kaushalmodi** [comment] 2018-02-16 04:46
.. no error on both bash and tcsh.

**Comment by kaushalmodi** [comment] 2018-02-16 04:48
> This is because $(echo "${piped_data}" | head -n 10) will run. Since head is closing the pipe after 10 lines echo complains.

That shouldn't get executed under normal conditions.. gets executed only if `-D` switch is used.

So I tried using the `-D` switch, but even then.. no error.

**Comment by sshaw** [comment] 2018-02-16 04:55
It does get executed. The string is interpolated which runs the subshell. This is then passed to `debug` which only _chooses_ to print if `-D` was given.  

GNU/Linux has different versions of `head` and Bash so this can be why you're not seeing the error.

**Comment by kaushalmodi** [comment] 2018-02-16 04:59
> It does get executed. The string is interpolated which runs the subshell. This is then passed to debug which only chooses to print if -D was given.

Ah, ok. Also the GNU/BSD issue is still not gone :P

You suggestion makes a lot of sense.. will work on fixing this. Thanks!

**Comment by kaushalmodi** [comment] 2018-02-16 05:02
> why not just cat to file immediately

I have never used `cat` to assign to file. What's the syntax? SO doesn't help.

**Comment by kaushalmodi** [comment] 2018-02-16 05:13
I have this fix on https://github.com/kaushalmodi/eless/tree/direct-cat-to-tempfile branch.. but `make test` freezes locally for me with that commit, though your git log example works.

**Comment by kaushalmodi** [comment] 2018-02-16 05:33
Test the master now.

**Comment by sshaw** [comment] 2018-02-16 05:47
👍

**Closed** 2018-02-16 05:56 UTC
Labels: enhancement
